[package]
name = "py-diffsol"
version = "0.1.0"
edition = "2021"

[lib]
name = "diffsol"

[dependencies]
diffsol = { version = "0.1.10", features = ["diffsl-llvm14" ] }
numpy = "0.21.0"
pyo3 = { version = "0.21.0", features = ["extension-module"] }
pyoil3 = { path = "./pyoil3" } # FIXME use git URI when public
rust-numpy = "0.1.0"
