[package]
name = "py-diffsol"
version = "0.1.0"
edition = "2021"

[lib]
name = "diffsol"

[dependencies]
diffsol = { version = "0.1.10", features = ["diffsl-llvm14"] }
numpy = "0.21.0"
pyo3 = "0.21.0"
ndarray = "0.15.0"
nalgebra = "0.29.0"
